# Generated by Django 3.0.8 on 2020-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_following_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='numFollowing',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
